### PR TITLE
Update readme before docs merge

### LINKED ISSUE #11: Update Readme doc to reflect new process
The main `README.md` file contains a draft of the actual QuickStart Guide V2 that we plan to PR to `docs.chocolatey.org`.

This doc needs to be updated to reflect the new process.

### PR DESCRIPTION
**Pull request by adilio**
Closes #11 .

Docs Enhancements:
- [X] Reference Readme for login details
- [X] Acknowledgement of second script process for Windows Server 2016 in the CCM setup, specifically for the IIS bits
- [X] Added script disclaimer about trusting code form the Internet
- [X] General cleanup and refinements to prepare for docs merge

### CODE REVIEW

**Comment by ryanrichter94** [comment]
I wouldn't merge this until we see the final readme that's generated after PR #47 is reviewed & merged. Otherwise LGTM 🚀

**Comment by steviecoaster** [comment]
FYI, I touched this in my PR, so you'll want to rebase this on your end @adilio

**Comment by adilio** [comment]
No problem 🙂

**Comment by adilio** [comment]
Hey @ryanrichter94 and @steviecoaster, this is ready for review and merge as well.

I am aware some of it looks funny (Youtube link at end), but I'm using formatting recommended by Steph previously, so I'm confident it'll be good.

**Review by adilio — COMMENTED** [review]
LGTM 🚀

**Review by ryanrichter94 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
