### PR TITLE
Generate Desktop README.hmtl file at end of setup process

### LINKED ISSUE #46: Emit Services information to desktop (Readme)
At the end of the entire process we need to drop a document on the desktop with url and default account information for all services provisioned as part of the guide.

### PR DESCRIPTION
**Pull request by steviecoaster**
This PR will add a README.html file to the Public Desktop profile of the server where setup has been executed.

Fixes #46

### CODE REVIEW

**Comment by adilio** [comment]
I'm just following Mukesh's lead, but he wants us to focus on minimizing steps the users have to perform.

To that end, could `New-QuickStartReadme` and `Start-C4bCleanup` be Helper Functions that could be called at the end of the Jenkins script? As we are already having it pop up all 3 web portals (CCM, Nexus, Jenkins) at the end of that script, it would make sense to pop up this fourth Readme page as the first tab there, after running these two functions.

Thoughts?

**Comment by adilio** [comment]
The focus has always been less steps for the user. This level of simplicity does require a little complexity under the hood. But to the user, should be seamless.

If our focus was to keep the scripts entirely modular to reuse them for a distributed solution, I'd agree with you. At a later stage, we'll look at that for sure. For now, I'd say we roll it in to the end of the Jenkins step. But since these would be functions that live in `Get-Helpers.ps1`, there's nothing to say we can't split them out later.

Hope that makes sense.

**Comment by adilio** [comment]
LGTM! 🚀

**Review by ryanrichter94 — APPROVED** [review]
LGTM 🚀

**Comment by adilio** [comment]
Waiting on @steviecoaster to clean up merge conflict issues, then we are good to merge.

**Comment by adilio** [comment]
On further discussion with @steviecoaster, we've agreed to back out of this PR, and create a new one to avoid major merge conflicts.

**Review by adilio — COMMENTED** [review]
backed out

**Pull request closed without merging**
