### PR TITLE
(#158) Secure Jenkins installation with an SSL Certificate

### LINKED ISSUE #91: Update README
I have been able to consistently reproduce a bug with the generation of the `Readme.html` file on the desktop:

```
New-QuickstartReadme : The term 'https://${HostName}:8443' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\choco-setup\files\Start-C4bJenkinsSetup.ps1:177 char:1
+ New-QuickstartReadme
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (https://${HostName}:8443:String) [New-QuickstartReadme], CommandNotFoun
   dException
    + FullyQualifiedErrorId : CommandNotFoundException,New-QuickstartReadme
```

This is called in the `Start-C4bJenkinsSetup.ps1`, and the code for this function is here:
https://github.com/chocolatey/choco-quickstart-scripts/blob/a0feced48042c190a904c24e3b0d5ae6fc123ef2/scripts/Get-Helpers.ps1#L1593-L1637

This error is new, and could be the result of not testing #84 throughly enough?

@steviecoaster , I'm assigning this to you Sir.

### LINKED ISSUE #158: Harden Jenkins with SSL?
## Is Your Feature Request Related To A Problem? Please describe.

Everything else web related is secured with an SSL certificate. Should Jenkins?

## Describe The Solution. Why is it needed?

Seems to make sense to harden Jenkins. Granted it's _meant_ to be accessed internally only, but we have had folks ask about it not using SSL, and this would provide the ability for folks to reach out from anywhere _should they choose and do the work to make that possible_.

### PR DESCRIPTION
**Pull request by steviecoaster**
## Description Of Changes

This PR applies the SSL certificate used to secure Nexus and Central Management to additionally secure the web interface of Jenkins, binding it to port 4443, as 8443 and 443 are in use by other services.

## Motivation and Context

This provides a better security posture to the overall system, and will allow administrators to expose the web interface to Jenkins more broadly if they so choose.

## Testing

Built QSG environment with changes in place

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [X] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #158 
Fixes #91 

## Change Checklist

* [x] Requires a change to the documentation
* [ ] Documentation has been updated
* [x] Tests to cover my changes, have been added
* [x] All new and existing tests passed.
* [x] PowerShell v2 compatibility checked.

### CODE REVIEW

**Comment by JPRuskin** [comment]
Only one remaining note of confusion here, for me - currently we do a lot of non-Jenkins operations at the end of the Jenkins script (e.g. launching browsers). Obviously with this change, the Jenkins script is now run _before_ the Set-SSL script. That's less than ideal. I don't have a preference on how we handle it, but I feel like we should (eventually) bring the readme / browser stuff out into `Start-C4bSetup` or something along those lines.

Thoughts, @steviecoaster @ryanrichter94 ?

**Review by JPRuskin — APPROVED** [review]

**Comment by JPRuskin** [comment]
Actually, we'll need to update [these docs](https://docs.chocolatey.org/en-us/c4b-environments/quick-start-environment/chocolatey-for-business-quick-start-guide) and the readme before merging this.

**Review by ryanrichter94 — COMMENTED** [review]
Get the following error when running `.\Set-SslSecuirty.ps1`:
```
PS C:\choco-setup\files> .\Set-SslSecurity.ps1
C:\choco-setup\files\Set-SslSecurity.ps1 : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ .\Set-SslSecurity.ps1
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SslSecurity.ps1], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Set-SslSecurity.ps1
```

**Comment by JPRuskin** [comment]
> Get the following error when running `.\Set-SslSecuirty.ps1`:
> 
> ```
> PS C:\choco-setup\files> .\Set-SslSecurity.ps1
> C:\choco-setup\files\Set-SslSecurity.ps1 : Parameter set cannot be resolved using the specified named parameters.
> At line:1 char:1
> + .\Set-SslSecurity.ps1
> + ~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Set-SslSecurity.ps1], ParameterBindingException
>     + FullyQualifiedErrorId : AmbiguousParameterSet,Set-SslSecurity.ps1
> ```

Ah, fun.

To check: the default behaviour you'd expect in that case is that it should generate a self-signed cert and use that, un-hardened?

**Comment by JPRuskin** [comment]
The change here ends up making the discussed parameter set the default, resulting in the following behaviours:

- With no parameters passed
    image
- With any given parameter passed, only the valid parameters should show up
    image

**Comment by JPRuskin** [comment]
This is good to go with the rebase / JRE changes, @ryanrichter94.

image

One failed test, but you know why that is!

**Comment by JPRuskin** [comment]
@ryanrichter94: Ran through with regular and wildcard certs, wildcard came out with a minor issue that the latest commit should have firmed up.

**Comment by JPRuskin** [comment]
Added the docs PR, to go along with this change.

**Review by ryanrichter94 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
